# ATTN: Make changes in _custom.yml (created with init.ps1)

Autohotkey Documentation:
	path: <A_AHKEXEPATH>
	menu: Autohotkey


# --------------------------------------- SCRIPT CONTROL


Reload script and ini:
	hotkey: ^#r
	label: DevReloadScript
	menu: ScriptControl


Reload script when saved:
	hotkey: ~^s
	label: DevReloadScriptWhenSaved


Suspend script:
	hotkey: ^#!r
	label: DevSuspend
	menu: ScriptControl


Open the console log:
	hotkey: Capslock & C
	label: OpenConsoleLogWindow


Emergency exit:
	hotkey: +^#!r
	label: DevEmergencyExit
	menu: ScriptControl


# --------------------------------------- GUI HELPERS BUILT INTO AUTOHOTKEY


List lines:
	hotkey: !F8
	label: DevListLines
	menu: Autohotkey


List hotkeys:
	hotkey: !F9
	label: DevListHotkeys
	menu: Autohotkey


Key history:
	hotkey: !F10
	label: DevKeyHistory
	menu: Autohotkey


List vars:
	hotkey: !F11
	label: DevListVars
	menu: Autohotkey


# TODO: get window info directly from active window
# https://github.com/AfterLemon/TooltipSpy
Spy window:
	hotkey: !F12
	titleMatcher: ahk_exe AU3_Spy.exe
	path:
		- <A_AHKPATH>\AU3_Spy.exe
		- <A_AHKPATH>\WindowSpy.ahk
	doublePressCloseHotkey: ESC
	menu: Autohotkey


Convert selected ahk file to exe:
	hotkey: !F7
	titleMatcher: ahk_exe Ahk2Exe.exe
	path: <A_AHKPATH>\Compiler\Ahk2Exe.exe
	label: ConvertAhkToExe
	menu: Autohotkey
