# ATTN: Make changes in _custom.yml (created with init.ps1)

Change casing of selected text:
	hotkey: ^#t
	followedBy:
		- desc: To Title Case
		  key: t
		  fn: ToTitleCase

		- desc: TO UPPER CASE
		  key: u
		  fn: ToUpperCase

		- desc: to lower case
		  key: l
		  fn: ToLowerCase

		- desc: Slugify
		  key: s
		  fn: Slugify


Translate C\Users\ to /c/Users/:
	label: PathWinToUnix
	hotkey: ^#x


Surround selected text with Markdown code block:
	label: MdCodeBlockSurround
	hotkey: !#m


New Markdown code block:
	label: MdCodeBlockNew
	hotkey: ^#!m

Base64 encode/decode selected text:
	hotkey: ^#b
	followedBy:
		- desc: Base64 encode
		  key: e
		  fn: Base64Encode

		- desc: Base64 decode
		  key: d
		  fn: Base64Decode

# TODO: make all these hotkeys start with AltGr?

# There is also LC_UrlEncode & LC_UrlDecode
Uri encode/decode selected text:
	hotkey: ^#u
	followedBy:
		- desc: Uri encode
		  key: e
		  fn: LC_UriEncode

		- desc: Uri decode
		  key: d
		  fn: LC_UriDecode
