# ATTN: Make changes in _custom.yml (created with init.ps1)

Change casing of selected text:
	label: TextTransform
	hotkey: ^#t


Translate C\Users\ to /c/Users/:
	label: PathWinToUnix
	hotkey: ^#x


Surround selected text with Markdown code block:
	label: MdCodeBlockSurround
	hotkey: !#m


New Markdown code block:
	label: MdCodeBlockNew
	hotkey: ^#!m

Encode/Decode Base64 (follow hotkey with 'e' or 'd'):
	label: EncodeDecodeBase64
	hotkey: ^#b
