# ATTN: Make changes in _custom.yml (created with init.ps1)

Calculator:
	hotkey: ^#c
	path: <A_WINDIR>\System32\calc.exe
	titleMatcher: ahk_class CalcFrame
	doublePressCloseHotkey: ~ESC # ~ --> First ESC should still clear the calc input
	menu: Applications


Paint.NET:
	hotkey: ^#d
	titleMatcher: ahk_exe PaintDotNet.exe
	path: <A_PROGRAMFILES>\paint.net\PaintDotNet.exe
	menu: Applications


Robo 3T (ex Robomongo):
	hotkey: CapsLock & Q
	titleMatcher: ahk_exe robo3t.exe
	path: <A_PROGRAMFILES>\Robo 3T 1.1.1\robo3t.exe
	menu: Applications


HeidiSql:
	hotkey: CapsLock & S
	titleMatcher: ahk_exe heidisql.exe
	path: <A_PROGRAMFILES>\HeidiSQL\heidisql.exe
	menu: Applications


DBeaver:
	path: <USERPROFILE>\AppData\Local\DBeaver\dbeaver.exe
	pathParams: -nl en
	menu: Applications


FileZilla:
	hotkey: ^#f
	titleMatcher: ahk_exe filezilla.exe
	path:
		- C:\Program Files\FileZilla FTP Client\filezilla.exe
		- C:\Program Files (x86)\FileZilla FTP Client\filezilla.exe
	menu: Applications


7-Zip:
	titleMatcher: ahk_exe 7zFM.exe
	path: <A_PROGRAMFILES>\7-zip\7zFM.exe
	menu: Applications


VLC:
	path: <A_PROGRAMFILES>\VideoLAN\VLC\vlc.exe
	menu: Applications


Beyond Compare:
	path:
		- C:\Program Files (x86)\Beyond Compare 3\BCompare.exe
		- C:\Program Files (x86)\Beyond Compare 4\BCompare.exe
	menu: Applications


DiffMerge:
	path: C:\Program Files\SourceGear\Common\DiffMerge\sgdm.exe
	menu: Applications


IrfanView:
	path:
		- C:\Program Files (x86)\IrfanView\i_view32.exe
		- C:\Program Files\IrfanView\i_view32.exe
	menu: Applications


TeamViewer:
	path: C:\Program Files (x86)\TeamViewer\TeamViewer.exe
	menu: Applications


dotPeek:
	path:
		- <USERPROFILE>\AppData\Local\JetBrains\Installations\dotPeek09\dotPeek64.exe
		- <USERPROFILE>\AppData\Local\JetBrains\Installations\dotPeek11\dotPeek64.exe
	menu: Applications


Ditto:
	path:
		- C:\Program Files (x86)\Ditto\Ditto.exe
		- C:\Program Files\Ditto\Ditto.exe
	menu: Applications
