Business tooling:
	hotkey: Capslock & b
	readFrom: selectedText
	writeTo: none
	followedBy:
		- desc: Validate IBAN nr
			key: b
			fn: ValidIBANAndInform
		- desc: Notice period
			key: o
			fn: CalculateNoticePeriod
