# ATTN: Make changes in _custom.yml (created with init.ps1)

ConvertToTitleCase:
	label: ConvertToTitleCase
	hotkey: ^#t



Surround selected text with Markdown code block:
	label: MdCodeBlockSurround
	hotkey: !#m


New Markdown code block:
	label: MdCodeBlockNew
	hotkey: ^#!m

