#
# Quick start applications
#

# A textual description:
# 	menu: Contextmenu name
# 	hotkey:
# 	path: path to the exe to start (string | array)
# 	pathParams: params passed to the exe
# 	label: either specify a path or this, an existing Autohotkey label
# 	titleMatcher:  ahk_class, ahk_exe or Regex
# 	doublePressCloseHotkey: ESC ; requires titleMatcher
# 	passExplorerPathAsArgument: dir OR file; When in Windows Explorer, pass path/selected files as parameter
# 	active: 0 ; To disable it
# 	asAdmin: 1
# 	explorerFilesSeparator: A_SPACE ; c:\file1 c:\file2 (a space by default)




# -------------------------------------------------------------------------------------------------------------- EDITORS


# Ctrl+Win+S: Default editor (see mike.ini)
Editor:
	hotkey: ^#s
	editor: 1
	passExplorerPathAsArgument: dir
	active: 1
	menu: Applications


# Win+C: Notepad++. C=Code? :) (N is already mapped to OneNote)
Notepad++:
	hotkey: "#c"
	titleMatcher: ahk_class Notepad++
	path:
		- C:\Program Files (x86)\Notepad++\Notepad++.exe
		- C:\Program Files\Notepad++\Notepad++.exe
	passExplorerPathAsArgument: file
	explorerFilesSeparator: \"
	active: 1
	menu: Applications


Notepad++ (New Window):
	hotkey: ^#!c
	titleMatcher: ahk_class Notepad++
	path:
		- C:\Program Files (x86)\Notepad++\Notepad++.exe
		- C:\Program Files\Notepad++\Notepad++.exe
	pathParams: -multiInst
	active: 1
	menu: Applications


PowerShell ISE:
	hotkey: !#r
	titleMatcher: ahk_exe powershell_ise.exe
	path: <A_WINDIR>\System32\WindowsPowerShell\v1.0\powershell_ise.exe
	openWithPathArgs: cmd.exe /s /c start /D "<path>" <exe> -file "<selectedFiles>"
	# Other ISE CLI arg: -NoProfile
	passExplorerPathAsArgument: file
	explorerFilesSeparator: ,
	active: 1
	menu: Applications




# ------------------------------------------------------------------------------------------------------------- CONSOLES
# TODO: cant open cmder with specific path:
# https://github.com/cmderdev/cmder/issues/91
Cmder:
	hotkey: +#c
	titleMatcher: ahk_exe ConEmu64.exe
	path:
		- C:\bin\cmder\Cmder.exe
		- C:\tools\cmder\Cmder.exe
	openWithPathArgs: <exe> /start <path>
	passExplorerPathAsArgument: dir
	active: 1
	menu: Consoles


# https://stackoverflow.com/questions/60904/how-can-i-open-a-cmd-window-in-a-specific-location
Command Prompt:
	hotkey: !#c
	titleMatcher: ahk_class ConsoleWindowClass
	path: C:\Windows\System32\cmd.exe
	passExplorerPathAsArgument: dir
	openWithPathArgs: <exe> /K "cd /d <path>"
	active: 1
	menu: Consoles


Command Prompt (Admin):
	hotkey: +!#c
	titleMatcher: ahk_class ConsoleWindowClass
	path: C:\Windows\System32\cmd.exe
	passExplorerPathAsArgument: dir
	openWithPathArgs: <exe> /K "cd /d <path>"
	asAdmin: 1
	active: 1
	menu: Consoles


PowerShell:
	hotkey: !#p
	titleMatcher: ahk_exe powershell.exe
	path: <A_WINDIR>\System32\WindowsPowerShell\v1.0\powershell.exe
	passExplorerPathAsArgument: dir
	openWithPathArgs: <exe> -noexit -command "cd '<path>'"
	active: 1
	menu: Consoles


PowerShell (Admin):
	hotkey: ^!#p
	titleMatcher: ahk_exe powershell.exe
	path: <A_WINDIR>\System32\WindowsPowerShell\v1.0\powershell.exe
	passExplorerPathAsArgument: dir
	openWithPathArgs: <exe> -noexit -command "cd '<path>'"
	asAdmin: 1
	active: 1
	menu: Consoles




# --------------------------------------------------------------------------------------------------------- APPLICATIONS

Calculator:
	hotkey: ^#c
	path: <A_WINDIR>\System32\calc.exe
	titleMatcher: ahk_class CalcFrame
	doublePressCloseHotkey: ~ESC # ~ --> First ESC should still clear the calc input
	active: 1
	menu: Applications


Paint.NET:
	hotkey: ^#d
	titleMatcher: ahk_exe PaintDotNet.exe
	path: <A_PROGRAMFILES>\paint.net\PaintDotNet.exe
	active: 1
	menu: Applications


Robo 3T (ex Robomongo):
	hotkey: CapsLock & Q
	titleMatcher: ahk_exe robo3t.exe
	path: <A_PROGRAMFILES>\Robo 3T 1.1.1\robo3t.exe
	active: 1
	menu: Applications


HeidiSql:
	hotkey: CapsLock & S
	titleMatcher: ahk_exe heidisql.exe
	path: <A_PROGRAMFILES>\HeidiSQL\heidisql.exe
	active: 1
	menu: Applications


FileZilla:
	hotkey: ^#f
	titleMatcher: ahk_exe filezilla.exe
	path: <A_PROGRAMFILES>\FileZilla FTP Client\filezilla.exe
	active: 1
	menu: Applications




# ------------------------------------------------------------------------------------------------------------ DEV TOOLS


Reload script and ini:
	active: 1
	hotkey: ^#r
	label: DevReloadScript


Reload script when saved:
	active: 1
	hotkey: ~^s
	label: DevReloadScriptWhenSaved


Reload script and ini:
	active: 1
	hotkey: ^#r
	label: DevReloadScript


Suspend script:
	active: 1
	hotkey: ^#!r
	label: DevSuspend


List hotkeys:
	active: 1
	hotkey: !F9
	label: DevListHotkeys
	menu: Autohotkey


Key history:
	active: 1
	hotkey: !F10
	label: DevKeyHistory
	menu: Autohotkey


List vars:
	active: 1
	hotkey: !F11
	label: DevListVars
	menu: Autohotkey


Spy window:
	hotkey: !F12
	titleMatcher: ahk_exe AU3_Spy.exe
	path:
		- <A_AHKPATH>\AU3_Spy.exe
		- <A_AHKPATH>\WindowSpy.ahk
	doublePressCloseHotkey: ESC
	active: 1
	menu: Autohotkey
