# --------------------------------------- WINDOW MANAGEMENT

Minimize all/restore minimized windows on active monitor:
	label: WindowsMinMax
	hotkey: ^!#D


# ----------------------------------------- CLIPBOARD STUFF


Append selected text to clipboard:
	label: AppendToClipboard
	hotkey: ^+#c


Translate C:\Users\ to /c/Users/:
	label: PathWinToUnix
	hotkey: ^#x



# ------------------------------------------ WINDOWS EXPLORER

Zip the current directory or selected files in Windows Explorer:
	label: ZipDirectory
	hotkey: ^#z
	context: explorer


Select the last downloaded file in Windows Explorer:
	label: ExplorerLastDownloadedFile
	hotkey: ^!d


Open Windows Explorer in path on clipboard:
	label: OpenExplorerInClipboardPath
	hotkey: Control & CapsLock


Open 2 Windows Explorers - On Downloads folder and on USB drive:
	label: CopyDownloadToUsb
	hotkey: <^>!#d


Create new file in Windows Explorer:
	label: ExplorerNewFile
	hotkey: ^+f
	context: explorer


Create new .txt file in Windows Explorer:
	label: ExplorerNewTextFile
	hotkey: ^+t
	context: explorer


2x Capslock - Put directory of selected file on clipboard:
	label: ExplorerSelectedFileDirToClipboard
	hotkey: CapsLock
	context: explorer


2x Shift + Capslock - Put full path of selected file on clipboard:
	label: ExplorerSelectedFilePathToClipboard
	hotkey: Shift & CapsLock
	context: explorer
