# --------------------------------------- WINDOW MANAGEMENT

Minimize all/restore minimized windows on active monitor:
  label: WindowsMinMax
  hotkey: ^!#D


# ----------------------------------------- CLIPBOARD STUFF


Append selected text to clipboard:
  label: AppendToClipboard
  hotkey: ^+#c




Open context menu on mouse cursor:
  hotkey: Capslock & m
  followedBy:
    - desc: Autohotkey
      key: a
      fn: ShowMenuAutohotkey

    - desc: Browsers
      key: b
      fn: ShowMenuBrowsers

    - desc: Consoles
      key: c
      fn: ShowMenuConsoles

    - desc: Editors
      key: e
      fn: ShowMenuEditors

    - desc: Programs
      key: p
      fn: ShowMenuPrograms

    - desc: Windows
      key: w
      fn: ShowMenuWindows
