# ATTN: Make changes in _custom.yml (created with init.ps1)

Zip the current directory or selected files in Windows Explorer:
	label: ZipDirectory
	hotkey: ^#z
	context: explorer


Select the last downloaded file in Windows Explorer:
	label: ExplorerLastDownloadedFile
	hotkey: ^!d


Open 2 Windows Explorers - On Downloads folder and on USB drive:
	label: CopyDownloadToUsb
	hotkey: <^>!#d


Create new file in Windows Explorer:
	label: ExplorerNewFile
	hotkey: ^+f
	context: explorer


Create new .txt file in Windows Explorer:
	label: ExplorerNewTextFile
	hotkey: ^+t
	context: explorer


Open Windows Explorer in path on clipboard:
	label: OpenExplorerInClipboardPath
	hotkey: $#E


2x Capslock - Put directory of selected file on clipboard:
	label: ExplorerSelectedFileDirToClipboard
	hotkey: CapsLock
	context: explorer


2x Shift + Capslock - Put full path of selected file on clipboard:
	label: ExplorerSelectedFilePathToClipboard
	hotkey: Shift & CapsLock
	context: explorer


See image dimensions and file size:
	desc: Press again to copy dimensions to clipboard
	hotkey: "#Enter"
	label: SeeImageDimensions
	context: explorer



Switch to Details View (builtin):
	desc: Resize first column so that filenames are completely visible
	hotkey: ~^+6 # This hotkey should probably not be changed (it matches the builtin hotkey)
	label: SwitchToDetailsView
	context: explorer



2x Esc closes Windows Explorer:
	titleMatcher: ahk_class CabinetWClass|ExploreWClass
	doublePressCloseHotkey: ~ESC
